/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test.table;

import java.awt.event.MouseAdapter;
import javax.swing.JDialog;
import javax.swing.JTable;
import javax.swing.JTextField;
import net.wirex.AppEngine;
import static net.wirex.EventMethod.MOUSE_CLICKED;
import net.wirex.annotations.Bind;
import net.wirex.annotations.Data;
import net.wirex.annotations.Event;
import net.wirex.annotations.EventContainer;

/**
 *
 * @author ritchie
 */
@Bind(model = TableModel.class, presenter = TablePresenter.class)
public class TablePanel extends javax.swing.JPanel {

    /**
     * Creates new form TablePanel
     */
    public TablePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = AppEngine.checkout(JTable.class, "table");
        jTextField1 = AppEngine.checkout(JTextField.class, "field1");
        jTextField2 = AppEngine.checkout(JTextField.class, "field2");
        jButton1 = new javax.swing.JButton();

        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Submit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                .addGap(76, 76, 76)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    @Event("submit2")
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    @Data(value="table", data="selectedRow")
    @EventContainer(listens = MouseAdapter.class,
        events = {
            @Event(value="read", at=MOUSE_CLICKED)
        }
    )
    private javax.swing.JTable jTable1;
    @Data("field1")
    private javax.swing.JTextField jTextField1;
    @Data("field2")
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    public static void main(String[] args) {
        AppEngine.prepare(TablePanel.class).display(JDialog.class);
    }
}
