/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package test.tree;

import javax.swing.JTree;
import net.wirex.ApplicationControllerFactory;
import net.wirex.annotations.Bind;
import net.wirex.annotations.Data;

/**
 *
 * @author RBORJA
 */
@Bind(model = MyTreeModel.class, presenter = MyTreePresenter.class)
public class MyTreeView extends javax.swing.JPanel {

    /**
     * Creates new form MyTreeView
     */
    public MyTreeView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = ApplicationControllerFactory.checkout(JTree.class, "tree");

        jScrollPane1.setViewportView(jTree1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    @Data("tree")
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
