/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package test.whole;

import com.visp.validex.EmailConstraintValidator;
import com.visp.validex.PasswordConstraintValidator;
import com.visp.validex.PhoneNumberConstraintValidator;
import com.visp.validex.UsernameValidator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JTextField;
import net.wirex.AppEngine;
import net.wirex.EventMethod;
import net.wirex.MVP;
import net.wirex.annotations.Balloon;
import net.wirex.annotations.Bind;
import net.wirex.annotations.Data;
import net.wirex.annotations.Event;
import net.wirex.annotations.EventContainer;
import net.wirex.annotations.Permit;
import net.wirex.annotations.Property;
import net.wirex.annotations.Rule;
import net.wirex.annotations.Text;
import net.wirex.exceptions.ViewClassNotBindedException;
import net.wirex.exceptions.WrongComponentException;
import test.another.NewLoginPanel;

/**
 *
 * @author ritchie
 */
@Property(ValidatorResource.class)
@Bind(model = ValidatorModel.class, presenter = ValidatorPresenter.class)
public class ValidatorPanel extends javax.swing.JPanel {

    /**
     * Creates new form ValidatorPanel
     */
    public ValidatorPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = AppEngine.checkout(JTextField.class, "username");
        jLabel1 = AppEngine.mediator("username");
        jLabel2 = AppEngine.mediator("password");
        jTextField2 = AppEngine.checkout(JTextField.class, "password");
        jLabel3 = AppEngine.mediator("retype");
        jTextField3 = AppEngine.checkout(JTextField.class, "retype");
        jLabel4 = AppEngine.mediator("email");
        jTextField4 = AppEngine.checkout(JTextField.class, "email");
        jLabel5 = AppEngine.mediator("phoneNumber");
        jTextField5 = AppEngine.checkout(JTextField.class, "phoneNumber");
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        jLabel3.setText("Retype");

        jLabel4.setText("Email");

        jLabel5.setText("Phone Number");

        jButton1.setText("Reset");

        jButton2.setText("Submit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String[] args) {
        try {
            AppEngine.setPermissionModel(MyPermissionLevel.class);
            MVP mvp2 = AppEngine.prepare(PermissionPanel.class);
            mvp2.display(JDialog.class, Boolean.TRUE);
            MVP mvp = AppEngine.prepare(ValidatorPanel.class);
            mvp.display(JDialog.class, Boolean.TRUE);
            
        } catch (ViewClassNotBindedException ex) {
            Logger.getLogger(ValidatorPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (WrongComponentException ex) {
            Logger.getLogger(ValidatorPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    @Event("reset")
    @Permit("reset")
    private javax.swing.JButton jButton1;
    @Event("submit")
    @Balloon(NewLoginPanel.class)
    private javax.swing.JButton jButton2;
    @Text("username")
    private javax.swing.JLabel jLabel1;
    @Text("password")
    private javax.swing.JLabel jLabel2;
    @Text("retype")
    private javax.swing.JLabel jLabel3;
    @Text("email")
    private javax.swing.JLabel jLabel4;
    @Text("phoneNumber")
    private javax.swing.JLabel jLabel5;
    @Data("username")
    @Balloon(text="Enter a valid username")
    @Rule(UsernameValidator.class)
    @Permit("username")
    private javax.swing.JTextField jTextField1;
    @Data("password")
    @Rule(PasswordConstraintValidator.class)
    @Permit("password")
    private javax.swing.JTextField jTextField2;
    @Data("retype")
    @Rule(PasswordConstraintValidator.class)
    @Permit("retype")
    private javax.swing.JTextField jTextField3;
    @Data("email")
    @Rule(EmailConstraintValidator.class)
    @Permit("email")
    private javax.swing.JTextField jTextField4;
    @Data("phoneNumber")
    @Rule(PhoneNumberConstraintValidator.class)
    @Permit("phoneNumber")
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
